### PR TITLE
Fix provider for slice arguments. fix #8

### LINKED ISSUE #8: Panic if using slice arguments
If using slice arguments in constructor, following panic messages.

```
panic: arg 1 of type "[]uint" cannot be assigned or converted to type "uint" for provider constructor ...
```

This error cause following code for variadic methods in provider.go

```
		if i < fnType.NumIn() {
			inType = fnType.In(i)
		} else {
			inType = fnType.In(fnType.NumIn() - 1)
		}

		if inType.Kind() == reflect.Slice {
			inType = inType.Elem()
		}
```

### PR DESCRIPTION
**Pull request by hori-ryota**
Fix provider for slice arguments. This bug cause changes for variadic methods.

```
$ go test ./...
?       github.com/karlkfi/inject       [no test files]
ok      github.com/karlkfi/inject/test  0.007s
?       github.com/karlkfi/inject/test/variadic [no test files]
```

### CODE REVIEW

**Comment by hori-ryota** [comment]
@karlkfi Would you be able to review this?

**Comment by hori-ryota** [comment]
fmm...

**Comment by karlkfi** [comment]
I’m not sure I understand what bug this fixes. Can you add a test case?

**Comment by hori-ryota** [comment]
Bug description is here.

[Add support for variadic arguments on provider constructor by mumia · Pull Request #7 · karlkfi/inject](https://github.com/karlkfi/inject/pull/7#issuecomment-334930922)

Example
```
func NewSomething(a, b int, c []int) Something

something.graph.Define(
        &something.Something,
        inject.NewProvider(
            something.NewSomething,
            0,
            1,
            []int{2,3,4,5},
        ),
    )
```
```
panic: arg 3 of type "[]int" cannot be assigned or converted to type "int" for provider constructor ...
```

It cause misunderstanding of slice to variadic arguments.

I'll try add test.

File: test/variadic_test.go [hunk 1]
```diff
@@ -58,12 +55,70 @@ func TestVariadicAll(t *testing.T) {
 	graph.Define(
 		&container,
 		inject.NewProvider(
-			func() *variadic.VariadicContainer{
```
Comment (hori-ryota) [inline test/variadic_test.go]: If wrapped here, variadic constructor will not tested.

**Comment by hori-ryota** [comment]
@karlkfi It was veeeeeeeeeeery late (sorry!!) but I added tests. 😄

**Review by karlkfi — APPROVED** [review]

**Comment by karlkfi** [comment]
Thanks! 
Passed manual tests.
Got Travis working again (it's been a while). 
Passed tests on Travis.
